### ISSUE TITLE
Help me understand of how things work in github

### ISSUE THREAD

**Issue by RamEase** [OpenSouceCode/Hacktoberfest2020#899]
I have been researching a lot on git and other version control systems.
Things I learned: 

- Version control systems help to manipulate and modify a project with an assurance of not destroying the base data.
- Git is different because it posts snapshots of files instead of the previous delta based system.

Problem I encountered here, in my first ever PR :
- Bad Agrim-Bansal.md markdown file
- Bad jaigora24.md markdown file

My question is, I corrected the problem in above mentioned markdown files and my PR was merged with main, **why does error in Agrim-Bansal.md & jaigora24.md remains in later PRs?**

Please reply kindly, I am new to this platform.
Thank you

**Comment by hiruthic2002** [comment]
You made the pull request to your forked repository or to the base repository?. If you've made PR to the forked repo then you should create the PR to the base repo from your forked repo. Maybe that's why the new commits didn't reflect the changes you did.
- And also if you have seen the button saying "Merge and Pull Request" when you make the PR then you most likely made the PR to the fork

Reason: The fork is just a copy of the original repo and any changes to that repo will not change the owner's repo. You will see an option saying "This branch is \<n\> commits ahead of \<Base repo name\>." at the top of the forked repo. And that's, where you will make PR to the owner and they, will merge it 

##### I am also new to Git/GitHub so confirm with someone else before you proceed

**Comment by RamEase** [comment]
Yes I forked the repository, but I submitted my PR in base repository.

I just went through the code and closely looked upon the PR I mentioned above; **the code is resolved** and **the PR were prior to my PR.**

Thank you @hiruthic2002 for your comment 😊
